Добавил валидацию
htmlacademy-javascript/1860785-kekstagram-25 pull request #8
Opened 2022-03-14 11:10 UTC by b0rskii

2022-03-15 14:25 UTC, Dima-Dim requested changes
https://htmlacademy-javascript.github.io/1860785-kekstagram-25/8/

GET https://htmlacademy-javascript.github.io/1860785-kekstagram-25/8/pristine/pristine.min.js net::ERR_ABORTED 404

Uncaught ReferenceError: Pristine is not defined
    at form.js:12:18

2022-03-16 06:18 UTC, b0rskii commented
Перепроверил, у меня всё работает. Что может быть не так?

2022-03-16 06:20 UTC, Dima-Dim commented
> Перепроверил, у меня всё работает. Что может быть не так?

Возможно проблема со сборкой. Написали авторам курса. Ждём от них ответа.

2022-03-18 08:12 UTC, Dima-Dim commented
Переопубликуй проект, говорят что починили.

2022-03-19 04:29 UTC, merged